// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzOUJZnEwqdhhZY8bp-S1VVNMLO8qVulc',
    appId: '1:1005255766300:web:58f40c44ca0285ea624ad9',
    messagingSenderId: '1005255766300',
    projectId: 'reddit-clone-33a05',
    authDomain: 'reddit-clone-33a05.firebaseapp.com',
    storageBucket: 'reddit-clone-33a05.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG3GRpEOe1vUoo3SNLUHPb7IfZ0V4doC0',
    appId: '1:1005255766300:android:2bfbade976329579624ad9',
    messagingSenderId: '1005255766300',
    projectId: 'reddit-clone-33a05',
    storageBucket: 'reddit-clone-33a05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiTM9Aez5tFDC_5rIsWw2mI8n3kzllPO0',
    appId: '1:1005255766300:ios:0ab1363f1fedfcb8624ad9',
    messagingSenderId: '1005255766300',
    projectId: 'reddit-clone-33a05',
    storageBucket: 'reddit-clone-33a05.appspot.com',
    iosClientId: '1005255766300-t52olmed0s8ugkfarjgfrt083po4s902.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiTM9Aez5tFDC_5rIsWw2mI8n3kzllPO0',
    appId: '1:1005255766300:ios:0ab1363f1fedfcb8624ad9',
    messagingSenderId: '1005255766300',
    projectId: 'reddit-clone-33a05',
    storageBucket: 'reddit-clone-33a05.appspot.com',
    iosClientId: '1005255766300-t52olmed0s8ugkfarjgfrt083po4s902.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditApp',
  );
}
